import * as React from "react";
import axios from "axios";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import Select from "@mui/material/Select";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import LoadingButton from "@mui/lab/LoadingButton";
import "./App.css";

const App = () => {
  const [category, setCategory] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [quote, setQuote] = React.useState("");

  const handleChange = (event) => {
    setCategory(event.target.value);
  };

  const buttonclick = () => {
    if (category === "random") {
      setLoading(true);
      const options = {
        method: "GET",
        url: "https://api.quotable.io/quotes/random",
      };
      axios
        .request(options)
        .then(function (response) {
          setQuote(response.data[0]?.content);
          setLoading(false);
        })
        .catch(function (error) {
          console.error(error);
        });
    } else {
      setLoading(true);
      const options = {
        method: "GET",
        url: `https://api.quotable.io/quotes?tags=${category}`,
      };
      axios
        .request(options)
        .then(function (response) {
          const randNum =
            Math.random() * (response.data.results.length - 0) + 0;
          const ind = Math.floor(randNum);
          setQuote(response.data.results[ind].content);
          setLoading(false);
        })
        .catch(function (error) {
          console.error(error);
        });
    }
    console.log(quote);
  };

  return (
    <div>
      <div className="bg">
        <div className="centerScreen">
          <Container>
            <Box>
              <p className="categoryLabel">
                Quotes can be generated by choosing a category in the below
                dropdown
              </p>
            </Box>
            <Box>
              <FormControl
                variant="standard"
                sx={{ m: 1, minWidth: 240 }}
                size="small"
              >
                <Select
                  labelId="demo-select-small-label"
                  id="demo-select-small"
                  value={category}
                  label="Category"
                  onChange={handleChange}
                >
                  <MenuItem value="random">Random</MenuItem>
                  <MenuItem value="technology">Technology</MenuItem>
                  <MenuItem value="history">History</MenuItem>
                  <MenuItem value="wisdom">Wisdom</MenuItem>
                </Select>
              </FormControl>
            </Box>
            <Box>
              <div>
                <LoadingButton
                  loading={loading}
                  variant="contained"
                  color="success"
                  onClick={buttonclick}
                >
                  Generate
                </LoadingButton>
              </div>
            </Box>
            <Box>
              <p className="quote">{quote}</p>
            </Box>
          </Container>
        </div>
      </div>
    </div>
  );
};

export default App;
