import * as React from "react";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import Select from "@mui/material/Select";
import Button from "@mui/material/Button";
import "./App.css";

const App = () => {
  const [age, setAge] = React.useState("");

  const handleChange = (event) => {
    setAge(event.target.value);
  };

  return (
    <div>
      <div className="bg"></div>
      <div className="dropdownContainer">
        <p className="categoryLabel">
          Quotes can be generated by choosing a category in the below dropdown
        </p>
        <FormControl
          variant="standard"
          sx={{ m: 1, minWidth: 240 }}
          size="small"
        >
          <Select
            labelId="demo-select-small-label"
            id="demo-select-small"
            value={age}
            label="Category"
            onChange={handleChange}
          >
            <MenuItem value={1}>Random</MenuItem>
            <MenuItem value={10}>Ten</MenuItem>
            <MenuItem value={20}>Twenty</MenuItem>
            <MenuItem value={30}>Thirty</MenuItem>
          </Select>
        </FormControl>
        <div>
          <Button variant="contained" color="success">Generate</Button>
        </div>
      </div>
    </div>
  );
};

export default App;
